
import React, { useState } from 'react';

const localPlayerFiles = {
  "melvin mastil": "/players/alg_melvin_mastil.jpg",
  "oussama benbot": "/players/alg_oussama_benbot.jpg",
  "luca zidane": "/players/alg_luca_zidane.jpg",
  "aissa mandi": "/players/alg_aissa_mandi.jpg",
  "achref abada": "/players/alg_achref_abada.jpg",
  "mohamed amine tougai": "/players/alg_mohamed_amine_tougai.jpg",
  "zineddine belaid": "/players/alg_zineddine_belaid.jpg",
  "jaouen hadjam": "/players/alg_jaouen_hadjam.jpg",
  "rayan ait nouri": "/players/alg_rayan_ait_nouri.jpg",
  "rafik belghali": "/players/alg_rafik_belghali.jpg",
  "ramy bensebaini": "/players/alg_ramy_bensebaini.jpg",
  "samir chergui": "/players/alg_samir_chergui.jpg",
  "ramiz zerrouki": "/players/alg_ramiz_zerrouki.jpg",
  "houssem aouar": "/players/alg_houssem_aouar.jpg",
  "fares chaibi": "/players/alg_fares_chaibi.jpg",
  "hicham boudaoui": "/players/alg_hicham_boudaoui.jpg",
  "nabil bentaleb": "/players/alg_nabil_bentaleb.jpg",
  "ibrahim maza": "/players/alg_ibrahim_maza.jpg",
  "yassine titraoui": "/players/alg_yassine_titraoui.jpg",
  "riyad mahrez": "/players/alg_riyad_mahrez.jpg",
  "amine gouiri": "/players/alg_amine_gouiri.jpg",
  "anis hadj moussa": "/players/alg_anis_hadj_moussa.jpg",
  "nadhir benbouali": "/players/alg_nadhir_benbouali.jpg",
  "mohamed amoura": "/players/alg_mohamed_amoura.jpg",
  "adil boulbina": "/players/alg_adil_boulbina.jpg",
  "vladimir petkovic": "/players/alg_vladimir_petkovic.jpg",
  "juan musso": "/players/arg_juan_musso.jpg",
  "geronimo rulli": "/players/arg_geronimo_rulli.jpg",
  "emiliano martinez": "/players/uru_emiliano_martinez.jpg",
  "marcos senesi": "/players/arg_marcos_senesi.jpg",
  "nicolas tagliafico": "/players/arg_nicolas_tagliafico.jpg",
  "gonzalo montiel": "/players/arg_gonzalo_montiel.jpg",
  "lisandro martinez": "/players/arg_lisandro_martinez.jpg",
  "cristian romero": "/players/arg_cristian_romero.jpg",
  "nicolas otamendi": "/players/arg_nicolas_otamendi.jpg",
  "facundo medina": "/players/arg_facundo_medina.jpg",
  "nahuel molina": "/players/arg_nahuel_molina.jpg",
  "leandro paredes": "/players/arg_leandro_paredes.jpg",
  "rodrigo de paul": "/players/arg_rodrigo_de_paul.jpg",
  "valentin barco": "/players/arg_valentin_barco.jpg",
  "giovani lo celso": "/players/arg_giovani_lo_celso.jpg",
  "exequiel palacios": "/players/arg_exequiel_palacios.jpg",
  "nico gonzalez": "/players/arg_nico_gonzalez.jpg",
  "alexis mac allister": "/players/arg_alexis_mac_allister.jpg",
  "enzo fernandez": "/players/arg_enzo_fernandez.jpg",
  "julian alvarez": "/players/arg_julian_alvarez.jpg",
  "lionel messi": "/players/arg_lionel_messi.jpg",
  "thiago almada": "/players/arg_thiago_almada.jpg",
  "giuliano simeone": "/players/arg_giuliano_simeone.jpg",
  "nico paz": "/players/arg_nico_paz.jpg",
  "jose manuel lopez": "/players/arg_jose_manuel_lopez.jpg",
  "lautaro martinez": "/players/arg_lautaro_martinez.jpg",
  "mathew ryan": "/players/aus_mathew_ryan.jpg",
  "paul izzo": "/players/aus_paul_izzo.jpg",
  "patrick beach": "/players/aus_patrick_beach.jpg",
  "milos degenek": "/players/aus_milos_degenek.jpg",
  "alessandro circati": "/players/aus_alessandro_circati.jpg",
  "jacob italiano": "/players/aus_jacob_italiano.jpg",
  "jason geria": "/players/aus_jason_geria.jpg",
  "kai trewin": "/players/aus_kai_trewin.jpg",
  "aziz behich": "/players/aus_aziz_behich.jpg",
  "harry souttar": "/players/aus_harry_souttar.jpg",
  "cameron burgess": "/players/aus_cameron_burgess.jpg",
  "lucas herrington": "/players/aus_lucas_herrington.jpg",
  "connor metcalfe": "/players/aus_connor_metcalfe.jpg",
  "aiden oneill": "/players/aus_aiden_oneill.jpg",
  "cameron devlin": "/players/aus_cameron_devlin.jpg",
  "jackson irvine": "/players/aus_jackson_irvine.jpg",
  "mathew leckie": "/players/aus_mathew_leckie.jpg",
  "mohamed toure": "/players/aus_mohamed_toure.jpg",
  "ajdin hrustic": "/players/aus_ajdin_hrustic.jpg",
  "awer mabil": "/players/aus_awer_mabil.jpg",
  "nestory irankunda": "/players/aus_nestory_irankunda.jpg",
  "cristian volpato": "/players/aus_cristian_volpato.jpg",
  "nishan velupillay": "/players/aus_nishan_velupillay.jpg",
  "tete yengi": "/players/aus_tete_yengi.jpg",
  "alexander schlager": "/players/aut_alexander_schlager.jpg",
  "florian wiegele": "/players/aut_florian_wiegele.jpg",
  "patrick pentz": "/players/aut_patrick_pentz.jpg",
  "david affengruber": "/players/aut_david_affengruber.jpg",
  "kevin danso": "/players/aut_kevin_danso.jpg",
  "stefan posch": "/players/aut_stefan_posch.jpg",
  "david alaba": "/players/aut_david_alaba.jpg",
  "philipp lienhart": "/players/aut_philipp_lienhart.jpg",
  "phillip mwene": "/players/aut_phillip_mwene.jpg",
  "marco friedl": "/players/aut_marco_friedl.jpg",
  "michael svoboda": "/players/aut_michael_svoboda.jpg",
  "xaver schlager": "/players/aut_xaver_schlager.jpg",
  "nicolas seiwald": "/players/aut_nicolas_seiwald.jpg",
  "marcel sabitzer": "/players/aut_marcel_sabitzer.jpg",
  "florian grillitsch": "/players/aut_florian_grillitsch.jpg",
  "carney chukwuemeka": "/players/aut_carney_chukwuemeka.jpg",
  "romano schmid": "/players/aut_romano_schmid.jpg",
  "dejan ljubicic": "/players/aut_dejan_ljubicic.jpg",
  "konrad laimer": "/players/aut_konrad_laimer.jpg",
  "alexander prass": "/players/aut_alexander_prass.jpg",
  "paul wanner": "/players/aut_paul_wanner.jpg",
  "alessandro schoepf": "/players/aut_alessandro_schoepf.jpg",
  "marko arnautovic": "/players/aut_marko_arnautovic.jpg",
  "michael gregoritsch": "/players/aut_michael_gregoritsch.jpg",
  "sasa kalajdzic": "/players/aut_sasa_kalajdzic.jpg",
  "patrick wimmer": "/players/aut_patrick_wimmer.jpg",
  "thibaut courtois": "/players/bel_thibaut_courtois.jpg",
  "senne lammens": "/players/bel_senne_lammens.jpg",
  "mike penders": "/players/bel_mike_penders.jpg",
  "zeno debast": "/players/bel_zeno_debast.jpg",
  "arthur theate": "/players/bel_arthur_theate.jpg",
  "brandon mechele": "/players/bel_brandon_mechele.jpg",
  "maxim de cuyper": "/players/bel_maxim_de_cuyper.jpg",
  "thomas meunier": "/players/bel_thomas_meunier.jpg",
  "koni de winter": "/players/bel_koni_de_winter.jpg",
  "joaquin seys": "/players/bel_joaquin_seys.jpg",
  "timothy castagne": "/players/bel_timothy_castagne.jpg",
  "nathan ngoy": "/players/bel_nathan_ngoy.jpg",
  "axel witsel": "/players/bel_axel_witsel.jpg",
  "kevin de bruyne": "/players/bel_kevin_de_bruyne.jpg",
  "youri tielemans": "/players/bel_youri_tielemans.jpg",
  "diego moreira": "/players/bel_diego_moreira.jpg",
  "hans vanaken": "/players/bel_hans_vanaken.jpg",
  "alexis saelemaekers": "/players/bel_alexis_saelemaekers.jpg",
  "nicolas raskin": "/players/bel_nicolas_raskin.jpg",
  "amadou onana": "/players/bel_amadou_onana.jpg",
  "romelu lukaku": "/players/bel_romelu_lukaku.jpg",
  "leandro trossard": "/players/bel_leandro_trossard.jpg",
  "jeremy doku": "/players/bel_jeremy_doku.jpg",
  "dodi lukebakio": "/players/bel_dodi_lukebakio.jpg",
  "charles de ketelaere": "/players/bel_charles_de_ketelaere.jpg",
  "nikola vasilj": "/players/bih_nikola_vasilj.jpg",
  "mladen jurkas": "/players/bih_mladen_jurkas.jpg",
  "martin zlomislic": "/players/bih_martin_zlomislic.jpg",
  "nihad mujakic": "/players/bih_nihad_mujakic.jpg",
  "dennis hadzikadunic": "/players/bih_dennis_hadzikadunic.jpg",
  "tarik muharemovic": "/players/bih_tarik_muharemovic.jpg",
  "sead kolasinac": "/players/bih_sead_kolasinac.jpg",
  "amar dedic": "/players/bih_amar_dedic.jpg",
  "nikola katic": "/players/bih_nikola_katic.jpg",
  "stjepan radeljic": "/players/bih_stjepan_radeljic.jpg",
  "arjan malic": "/players/bih_arjan_malic.jpg",
  "benjamin tahirovic": "/players/bih_benjamin_tahirovic.jpg",
  "armin gigovic": "/players/bih_armin_gigovic.jpg",
  "ivan basic": "/players/bih_ivan_basic.jpg",
  "ivan sunjic": "/players/bih_ivan_sunjic.jpg",
  "amar memic": "/players/bih_amar_memic.jpg",
  "amir hadziahmetovic": "/players/bih_amir_hadziahmetovic.jpg",
  "dzenis burnic": "/players/bih_dzenis_burnic.jpg",
  "ermin mahmic": "/players/bih_ermin_mahmic.jpg",
  "samed bazdar": "/players/bih_samed_bazdar.jpg",
  "ermedin demirovic": "/players/bih_ermedin_demirovic.jpg",
  "edin dzeko": "/players/bih_edin_dzeko.jpg",
  "kerim alajbegovic": "/players/bih_kerim_alajbegovic.jpg",
  "esmir bajraktarevic": "/players/bih_esmir_bajraktarevic.jpg",
  "haris tabakovic": "/players/bih_haris_tabakovic.jpg",
  "jovo lukic": "/players/bih_jovo_lukic.jpg",
  "alisson": "/players/bra_alisson.jpg",
  "weverton": "/players/bra_weverton.jpg",
  "ederson": "/players/bra_ederson.jpg",
  "gabriel magalhaes": "/players/bra_gabriel_magalhaes.jpg",
  "marquinhos": "/players/bra_marquinhos.jpg",
  "alex sandro": "/players/bra_alex_sandro.jpg",
  "danilo": "/players/bra_danilo.jpg",
  "bremer": "/players/bra_bremer.jpg",
  "leo pereira": "/players/bra_leo_pereira.jpg",
  "douglas santos": "/players/bra_douglas_santos.jpg",
  "roger ibanez": "/players/bra_roger_ibanez.jpg",
  "ederson silva": "/players/bra_ederson_silva.jpg",
  "casemiro": "/players/bra_casemiro.jpg",
  "bruno guimaraes": "/players/bra_bruno_guimaraes.jpg",
  "fabinho": "/players/bra_fabinho.jpg",
  "danilo santos": "/players/bra_danilo_santos.jpg",
  "lucas paqueta": "/players/bra_lucas_paqueta.jpg",
  "vinicius junior": "/players/bra_vinicius_junior.jpg",
  "matheus cunha": "/players/bra_matheus_cunha.jpg",
  "neymar jr": "/players/bra_neymar_jr.jpg",
  "raphinha": "/players/bra_raphinha.jpg",
  "endrick": "/players/bra_endrick.jpg",
  "luiz henrique": "/players/bra_luiz_henrique.jpg",
  "gabriel martinelli": "/players/bra_gabriel_martinelli.jpg",
  "igor thiago": "/players/bra_igor_thiago.jpg",
  "rayan": "/players/bra_rayan.jpg",
  "dayne st. clair": "/players/can_dayne_st_clair.jpg",
  "maxime crepeau": "/players/can_maxime_crepeau.jpg",
  "owen goodman": "/players/can_owen_goodman.jpg",
  "alistair johnston": "/players/can_alistair_johnston.jpg",
  "alfie jones": "/players/can_alfie_jones.jpg",
  "luc de fougerolles": "/players/can_luc_de_fougerolles.jpg",
  "joel waterman": "/players/can_joel_waterman.jpg",
  "derek cornelius": "/players/can_derek_cornelius.jpg",
  "moise bombito": "/players/can_moise_bombito.jpg",
  "alphonso davies": "/players/can_alphonso_davies.jpg",
  "richie laryea": "/players/can_richie_laryea.jpg",
  "niko sigur": "/players/can_niko_sigur.jpg",
  "mathieu choiniere": "/players/can_mathieu_choiniere.jpg",
  "stephen eustaquio": "/players/can_stephen_eustaquio.jpg",
  "ismael kone": "/players/can_ismael_kone.jpg",
  "liam millar": "/players/can_liam_millar.jpg",
  "jacob shaffelburg": "/players/can_jacob_shaffelburg.jpg",
  "jonathan osorio": "/players/can_jonathan_osorio.jpg",
  "nathan saliba": "/players/can_nathan_saliba.jpg",
  "cyle larin": "/players/can_cyle_larin.jpg",
  "jonathan david": "/players/can_jonathan_david.jpg",
  "tani oluwaseyi": "/players/can_tani_oluwaseyi.jpg",
  "tajon buchanan": "/players/can_tajon_buchanan.jpg",
  "ali ahmed": "/players/can_ali_ahmed.jpg",
  "promise david": "/players/can_promise_david.jpg",
  "jayden nelson": "/players/can_jayden_nelson.jpg",
  "vozinha": "/players/cpv_vozinha.jpg",
  "marcio rosa": "/players/cpv_marcio_rosa.jpg",
  "cj dos santos": "/players/cpv_cj_dos_santos.jpg",
  "stopira": "/players/cpv_stopira.jpg",
  "diney borges": "/players/cpv_diney_borges.jpg",
  "pico lopes": "/players/cpv_pico_lopes.jpg",
  "logan costa": "/players/cpv_logan_costa.jpg",
  "sidny lopes cabral": "/players/cpv_sidny_lopes_cabral.jpg",
  "steven moreira": "/players/cpv_steven_moreira.jpg",
  "wagner pina": "/players/cpv_wagner_pina.jpg",
  "kelvin pires": "/players/cpv_kelvin_pires.jpg",
  "kevin pina": "/players/cpv_kevin_pina.jpg",
  "jovane cabral": "/players/cpv_jovane_cabral.jpg",
  "joao paulo": "/players/cpv_joao_paulo.jpg",
  "jamiro monteiro": "/players/cpv_jamiro_monteiro.jpg",
  "garry rodrigues": "/players/cpv_garry_rodrigues.jpg",
  "deroy duarte": "/players/cpv_deroy_duarte.jpg",
  "laros duarte": "/players/cpv_laros_duarte.jpg",
  "yannick semedo": "/players/cpv_yannick_semedo.jpg",
  "willy semedo": "/players/cpv_willy_semedo.jpg",
  "telmo arcanjo": "/players/cpv_telmo_arcanjo.jpg",
  "nuno da costa": "/players/cpv_nuno_da_costa.jpg",
  "helio varela": "/players/cpv_helio_varela.jpg",
  "gilson benchimol": "/players/cpv_gilson_benchimol.jpg",
  "dailon livramento": "/players/cpv_dailon_livramento.jpg",
  "ryan mendes": "/players/cpv_ryan_mendes.jpg",
  "david ospina": "/players/col_david_ospina.jpg",
  "camilo vargas": "/players/col_camilo_vargas.jpg",
  "alvaro montero": "/players/col_alvaro_montero.jpg",
  "daniel munoz": "/players/col_daniel_munoz.jpg",
  "jhon lucumi": "/players/col_jhon_lucumi.jpg",
  "santiago arias": "/players/col_santiago_arias.jpg",
  "yerry mina": "/players/col_yerry_mina.jpg",
  "gustavo puerta": "/players/col_gustavo_puerta.jpg",
  "johan mojica": "/players/col_johan_mojica.jpg",
  "willer ditta": "/players/col_willer_ditta.jpg",
  "deiver machado": "/players/col_deiver_machado.jpg",
  "davinson sanchez": "/players/col_davinson_sanchez.jpg",
  "kevin castano": "/players/col_kevin_castano.jpg",
  "richard rios": "/players/col_richard_rios.jpg",
  "jorge carrascal": "/players/col_jorge_carrascal.jpg",
  "james rodriguez": "/players/col_james_rodriguez.jpg",
  "jhon arias": "/players/col_jhon_arias.jpg",
  "juan portilla": "/players/col_juan_portilla.jpg",
  "jefferson lerma": "/players/col_jefferson_lerma.jpg",
  "juan quintero": "/players/col_juan_quintero.jpg",
  "luis diaz": "/players/col_luis_diaz.jpg",
  "jhon cordoba": "/players/col_jhon_cordoba.jpg",
  "cucho hernandez": "/players/col_cucho_hernandez.jpg",
  "jaminton campaz": "/players/col_jaminton_campaz.jpg",
  "luis suarez": "/players/col_luis_suarez.jpg",
  "andres gomez": "/players/col_andres_gomez.jpg",
  "lionel mpasi": "/players/cod_lionel_mpasi.jpg",
  "timothy fayulu": "/players/cod_timothy_fayulu.jpg",
  "matthieu epolo": "/players/cod_matthieu_epolo.jpg",
  "steve kapuadi": "/players/cod_steve_kapuadi.jpg",
  "axel tuanzebe": "/players/cod_axel_tuanzebe.jpg",
  "dylan batubinsika": "/players/cod_dylan_batubinsika.jpg",
  "joris kayembe": "/players/cod_joris_kayembe.jpg",
  "chancel mbemba": "/players/cod_chancel_mbemba.jpg",
  "gedeon kalulu": "/players/cod_gedeon_kalulu.jpg",
  "arthur masuaku": "/players/cod_arthur_masuaku.jpg",
  "ngalayel mukau": "/players/cod_ngalayel_mukau.jpg",
  "nathanael mbuku": "/players/cod_nathanael_mbuku.jpg",
  "samuel moutoussamy": "/players/cod_samuel_moutoussamy.jpg",
  "theo bongonda": "/players/cod_theo_bongonda.jpg",
  "noah sadiki": "/players/cod_noah_sadiki.jpg",
  "aaron tshibola": "/players/cod_aaron_tshibola.jpg",
  "charles pickel": "/players/cod_charles_pickel.jpg",
  "edo kayembe": "/players/cod_edo_kayembe.jpg",
  "brian cipenga": "/players/cod_brian_cipenga.jpg",
  "gael kakuta": "/players/cod_gael_kakuta.jpg",
  "meschack elia": "/players/cod_meschack_elia.jpg",
  "cedric bakambu": "/players/cod_cedric_bakambu.jpg",
  "fiston mayele": "/players/cod_fiston_mayele.jpg",
  "yoane wissa": "/players/cod_yoane_wissa.jpg",
  "simon banza": "/players/cod_simon_banza.jpg",
  "yahia fofana": "/players/civ_yahia_fofana.jpg",
  "mohamed kone": "/players/civ_mohamed_kone.jpg",
  "alban lafont": "/players/civ_alban_lafont.jpg",
  "ousmane diomande": "/players/civ_ousmane_diomande.jpg",
  "ghislain konan": "/players/civ_ghislain_konan.jpg",
  "wilfried singo": "/players/civ_wilfried_singo.jpg",
  "odilon kossounou": "/players/civ_odilon_kossounou.jpg",
  "christopher operi": "/players/civ_christopher_operi.jpg",
  "guela doue": "/players/civ_guela_doue.jpg",
  "emmanuel agbadou": "/players/civ_emmanuel_agbadou.jpg",
  "evan ndicka": "/players/civ_evan_ndicka.jpg",
  "jean michael seri": "/players/civ_jean_michael_seri.jpg",
  "seko fofana": "/players/civ_seko_fofana.jpg",
  "franck kessie": "/players/civ_franck_kessie.jpg",
  "ibrahim sangare": "/players/civ_ibrahim_sangare.jpg",
  "parfait guiagon": "/players/civ_parfait_guiagon.jpg",
  "christ inao oulai": "/players/civ_christ_inao_oulai.jpg",
  "simon adingra": "/players/civ_simon_adingra.jpg",
  "yan diomande": "/players/civ_yan_diomande.jpg",
  "elye wahi": "/players/civ_elye_wahi.jpg",
  "oumar diakite": "/players/civ_oumar_diakite.jpg",
  "amad diallo": "/players/civ_amad_diallo.jpg",
  "nicolas pepe": "/players/civ_nicolas_pepe.jpg",
  "evann guessand": "/players/civ_evann_guessand.jpg",
  "bazoumana toure": "/players/civ_bazoumana_toure.jpg",
  "dominik livakovic": "/players/cro_dominik_livakovic.jpg",
  "ivor pandur": "/players/cro_ivor_pandur.jpg",
  "dominik kotarski": "/players/cro_dominik_kotarski.jpg",
  "josip stanisic": "/players/cro_josip_stanisic.jpg",
  "marin pongracic": "/players/cro_marin_pongracic.jpg",
  "josko gvardiol": "/players/cro_josko_gvardiol.jpg",
  "josip sutalo": "/players/cro_josip_sutalo.jpg",
  "kristijan jakic": "/players/cro_kristijan_jakic.jpg",
  "luka vuskovic": "/players/cro_luka_vuskovic.jpg",
  "martin erlic": "/players/cro_martin_erlic.jpg",
  "nikola moro": "/players/cro_nikola_moro.jpg",
  "mateo kovacic": "/players/cro_mateo_kovacic.jpg",
  "luka modric": "/players/cro_luka_modric.jpg",
  "nikola vlasic": "/players/cro_nikola_vlasic.jpg",
  "mario pasalic": "/players/cro_mario_pasalic.jpg",
  "martin baturina": "/players/cro_martin_baturina.jpg",
  "petar sucic": "/players/cro_petar_sucic.jpg",
  "toni fruk": "/players/cro_toni_fruk.jpg",
  "luka sucic": "/players/cro_luka_sucic.jpg",
  "andrej kramaric": "/players/cro_andrej_kramaric.jpg",
  "ante budimir": "/players/cro_ante_budimir.jpg",
  "ivan perisic": "/players/cro_ivan_perisic.jpg",
  "igor matanovic": "/players/cro_igor_matanovic.jpg",
  "marco pasalic": "/players/cro_marco_pasalic.jpg",
  "eloy room": "/players/cuw_eloy_room.jpg",
  "tyrick bodak": "/players/cuw_tyrick_bodak.jpg",
  "trevor doornbusch": "/players/cuw_trevor_doornbusch.jpg",
  "shurandy sambo": "/players/cuw_shurandy_sambo.jpg",
  "jurien gaari": "/players/cuw_jurien_gaari.jpg",
  "roshon van eijma": "/players/cuw_roshon_van_eijma.jpg",
  "sherel floranus": "/players/cuw_sherel_floranus.jpg",
  "armando obispo": "/players/cuw_armando_obispo.jpg",
  "joshua brenet": "/players/cuw_joshua_brenet.jpg",
  "riechedly bazoer": "/players/cuw_riechedly_bazoer.jpg",
  "deveron fonville": "/players/cuw_deveron_fonville.jpg",
  "godfried roemeratoe": "/players/cuw_godfried_roemeratoe.jpg",
  "juninho bacuna": "/players/cuw_juninho_bacuna.jpg",
  "livano comenencia": "/players/cuw_livano_comenencia.jpg",
  "leandro bacuna": "/players/cuw_leandro_bacuna.jpg",
  "arjany martha": "/players/cuw_arjany_martha.jpg",
  "tahith chong": "/players/cuw_tahith_chong.jpg",
  "kevin felida": "/players/cuw_kevin_felida.jpg",
  "juergen locadia": "/players/cuw_juergen_locadia.jpg",
  "jeremy antonisse": "/players/cuw_jeremy_antonisse.jpg",
  "sontje hansen": "/players/cuw_sontje_hansen.jpg",
  "tyrese noslin": "/players/cuw_tyrese_noslin.jpg",
  "kenji gorre": "/players/cuw_kenji_gorre.jpg",
  "jearl margaritha": "/players/cuw_jearl_margaritha.jpg",
  "brandley kuwas": "/players/cuw_brandley_kuwas.jpg",
  "gervane kastaneer": "/players/cuw_gervane_kastaneer.jpg",
  "matej kovar": "/players/cze_matej_kovar.jpg",
  "jindrich stanek": "/players/cze_jindrich_stanek.jpg",
  "lukas hornicek": "/players/cze_lukas_hornicek.jpg",
  "david zima": "/players/cze_david_zima.jpg",
  "tomas holes": "/players/cze_tomas_holes.jpg",
  "robin hranac": "/players/cze_robin_hranac.jpg",
  "vladimir coufal": "/players/cze_vladimir_coufal.jpg",
  "stepan chaloupek": "/players/cze_stepan_chaloupek.jpg",
  "ladislav krejci": "/players/cze_ladislav_krejci.jpg",
  "david jurasek": "/players/cze_david_jurasek.jpg",
  "jaroslav zeleny": "/players/cze_jaroslav_zeleny.jpg",
  "david doudera": "/players/cze_david_doudera.jpg",
  "vladimir darida": "/players/cze_vladimir_darida.jpg",
  "lukas cerv": "/players/cze_lukas_cerv.jpg",
  "lukas provod": "/players/cze_lukas_provod.jpg",
  "michal sadilek": "/players/cze_michal_sadilek.jpg",
  "tomas soucek": "/players/cze_tomas_soucek.jpg",
  "alexandr sojka": "/players/cze_alexandr_sojka.jpg",
  "hugo sochurek": "/players/cze_hugo_sochurek.jpg",
  "adam hlozek": "/players/cze_adam_hlozek.jpg",
  "patrik schick": "/players/cze_patrik_schick.jpg",
  "jan kuchta": "/players/cze_jan_kuchta.jpg",
  "mojmir chytil": "/players/cze_mojmir_chytil.jpg",
  "pavel sulc": "/players/cze_pavel_sulc.jpg",
  "tomas chory": "/players/cze_tomas_chory.jpg",
  "denis visinsky": "/players/cze_denis_visinsky.jpg",
  "hernan galindez": "/players/ecu_hernan_galindez.jpg",
  "moises ramirez": "/players/ecu_moises_ramirez.jpg",
  "gonzalo valle": "/players/ecu_gonzalo_valle.jpg",
  "felix torres": "/players/ecu_felix_torres.jpg",
  "piero hincapie": "/players/ecu_piero_hincapie.jpg",
  "joel ordonez": "/players/ecu_joel_ordonez.jpg",
  "willian pacho": "/players/ecu_willian_pacho.jpg",
  "pervis estupinan": "/players/ecu_pervis_estupinan.jpg",
  "angelo preciado": "/players/ecu_angelo_preciado.jpg",
  "jackson porozo": "/players/ecu_jackson_porozo.jpg",
  "yaimar medina": "/players/ecu_yaimar_medina.jpg",
  "jordy alcivar": "/players/ecu_jordy_alcivar.jpg",
  "anthony valencia": "/players/ecu_anthony_valencia.jpg",
  "kendry paez": "/players/ecu_kendry_paez.jpg",
  "alan minda": "/players/ecu_alan_minda.jpg",
  "pedro vite": "/players/ecu_pedro_vite.jpg",
  "denil castillo": "/players/ecu_denil_castillo.jpg",
  "alan franco": "/players/ecu_alan_franco.jpg",
  "moises caicedo": "/players/ecu_moises_caicedo.jpg",
  "john yeboah": "/players/ecu_john_yeboah.jpg",
  "kevin rodriguez": "/players/ecu_kevin_rodriguez.jpg",
  "enner valencia": "/players/ecu_enner_valencia.jpg",
  "jordy caicedo": "/players/ecu_jordy_caicedo.jpg",
  "gonzalo plata": "/players/ecu_gonzalo_plata.jpg",
  "nilson angulo": "/players/ecu_nilson_angulo.jpg",
  "mohamed elshenawy": "/players/egy_mohamed_elshenawy.jpg",
  "mahdy soliman": "/players/egy_mahdy_soliman.jpg",
  "mostafa shoubir": "/players/egy_mostafa_shoubir.jpg",
  "mohamed alaa": "/players/egy_mohamed_alaa.jpg",
  "yasser ibrahim": "/players/egy_yasser_ibrahim.jpg",
  "mohamed hany": "/players/egy_mohamed_hany.jpg",
  "hossam abdelmaguid": "/players/egy_hossam_abdelmaguid.jpg",
  "ramy rabia": "/players/egy_ramy_rabia.jpg",
  "mohamed abdelmoneim": "/players/egy_mohamed_abdelmoneim.jpg",
  "ahmed fatouh": "/players/egy_ahmed_fatouh.jpg",
  "karim hafez": "/players/egy_karim_hafez.jpg",
  "tarek alaa": "/players/egy_tarek_alaa.jpg",
  "emam ashour": "/players/egy_emam_ashour.jpg",
  "mostafa zico": "/players/egy_mostafa_zico.jpg",
  "hamdy fathy": "/players/egy_hamdy_fathy.jpg",
  "mohanad lashin": "/players/egy_mohanad_lashin.jpg",
  "nabil donga": "/players/egy_nabil_donga.jpg",
  "marawan attia": "/players/egy_marawan_attia.jpg",
  "mahmoud saber": "/players/egy_mahmoud_saber.jpg",
  "trezeguet": "/players/egy_trezeguet.jpg",
  "hamza abdelkarim": "/players/egy_hamza_abdelkarim.jpg",
  "mohamed salah": "/players/egy_mohamed_salah.jpg",
  "haissem hassan": "/players/egy_haissem_hassan.jpg",
  "ibrahim adel": "/players/egy_ibrahim_adel.jpg",
  "omar marmoush": "/players/egy_omar_marmoush.jpg",
  "zizo": "/players/egy_zizo.jpg",
  "dean henderson": "/players/eng_dean_henderson.jpg",
  "james trafford": "/players/eng_james_trafford.jpg",
  "ezri konsa": "/players/eng_ezri_konsa.jpg",
  "nico oreilly": "/players/eng_nico_oreilly.jpg",
  "john stones": "/players/eng_john_stones.jpg",
  "marc guehi": "/players/eng_marc_guehi.jpg",
  "trevoh chalobah": "/players/eng_trevoh_chalobah.jpg",
  "dan burn": "/players/eng_dan_burn.jpg",
  "reece james": "/players/eng_reece_james.jpg",
  "djed spence": "/players/eng_djed_spence.jpg",
  "jarell quansah": "/players/eng_jarell_quansah.jpg",
  "declan rice": "/players/eng_declan_rice.jpg",
  "elliot anderson": "/players/eng_elliot_anderson.jpg",
  "jude bellingham": "/players/eng_jude_bellingham.jpg",
  "kobbie mainoo": "/players/eng_kobbie_mainoo.jpg",
  "morgan rogers": "/players/eng_morgan_rogers.jpg",
  "eberechi eze": "/players/eng_eberechi_eze.jpg",
  "bukayo saka": "/players/eng_bukayo_saka.jpg",
  "harry kane": "/players/eng_harry_kane.jpg",
  "marcus rashford": "/players/eng_marcus_rashford.jpg",
  "anthony gordon": "/players/eng_anthony_gordon.jpg",
  "ollie watkins": "/players/eng_ollie_watkins.jpg",
  "noni madueke": "/players/eng_noni_madueke.jpg",
  "ivan toney": "/players/eng_ivan_toney.jpg",
  "brice samba": "/players/fra_brice_samba.jpg",
  "mike maignan": "/players/fra_mike_maignan.jpg",
  "robin risser": "/players/fra_robin_risser.jpg",
  "malo gusto": "/players/fra_malo_gusto.jpg",
  "lucas digne": "/players/fra_lucas_digne.jpg",
  "dayot upamecano": "/players/fra_dayot_upamecano.jpg",
  "jules kounde": "/players/fra_jules_kounde.jpg",
  "ibrahima konate": "/players/fra_ibrahima_konate.jpg",
  "william saliba": "/players/fra_william_saliba.jpg",
  "theo hernandez": "/players/fra_theo_hernandez.jpg",
  "lucas hernandez": "/players/fra_lucas_hernandez.jpg",
  "maxence lacroix": "/players/fra_maxence_lacroix.jpg",
  "manu kone": "/players/fra_manu_kone.jpg",
  "aurelien tchouameni": "/players/fra_aurelien_tchouameni.jpg",
  "ngolo kante": "/players/fra_ngolo_kante.jpg",
  "adrien rabiot": "/players/fra_adrien_rabiot.jpg",
  "rayan cherki": "/players/fra_rayan_cherki.jpg",
  "maghnes akliouche": "/players/fra_maghnes_akliouche.jpg",
  "ousmane dembele": "/players/fra_ousmane_dembele.jpg",
  "marcus thuram": "/players/fra_marcus_thuram.jpg",
  "kylian mbappe": "/players/fra_kylian_mbappe.jpg",
  "michael olise": "/players/fra_michael_olise.jpg",
  "bradley barcola": "/players/fra_bradley_barcola.jpg",
  "desire doue": "/players/fra_desire_doue.jpg",
  "manuel neuer": "/players/ger_manuel_neuer.jpg",
  "oliver baumann": "/players/ger_oliver_baumann.jpg",
  "alexander nuebel": "/players/ger_alexander_nuebel.jpg",
  "antonio ruediger": "/players/ger_antonio_ruediger.jpg",
  "waldemar anton": "/players/ger_waldemar_anton.jpg",
  "jonathan tah": "/players/ger_jonathan_tah.jpg",
  "joshua kimmich": "/players/ger_joshua_kimmich.jpg",
  "nico schlotterbeck": "/players/ger_nico_schlotterbeck.jpg",
  "nathaniel brown": "/players/ger_nathaniel_brown.jpg",
  "david raum": "/players/ger_david_raum.jpg",
  "malick thiaw": "/players/ger_malick_thiaw.jpg",
  "aleksandar pavlovic": "/players/ger_aleksandar_pavlovic.jpg",
  "leon goretzka": "/players/ger_leon_goretzka.jpg",
  "jamie leweling": "/players/ger_jamie_leweling.jpg",
  "jamal musiala": "/players/ger_jamal_musiala.jpg",
  "pascal gross": "/players/ger_pascal_gross.jpg",
  "angelo stiller": "/players/ger_angelo_stiller.jpg",
  "florian wirtz": "/players/ger_florian_wirtz.jpg",
  "leroy sane": "/players/ger_leroy_sane.jpg",
  "nadiem amiri": "/players/ger_nadiem_amiri.jpg",
  "felix nmecha": "/players/ger_felix_nmecha.jpg",
  "assan ouedraogo": "/players/ger_assan_ouedraogo.jpg",
  "kai havertz": "/players/ger_kai_havertz.jpg",
  "nick woltemade": "/players/ger_nick_woltemade.jpg",
  "maximilian beier": "/players/ger_maximilian_beier.jpg",
  "deniz undav": "/players/ger_deniz_undav.jpg",
  "lawrence ati zigi": "/players/gha_lawrence_ati_zigi.jpg",
  "joseph anang": "/players/gha_joseph_anang.jpg",
  "benjamin asare": "/players/gha_benjamin_asare.jpg",
  "alidu seidu": "/players/gha_alidu_seidu.jpg",
  "jonas adjetey": "/players/gha_jonas_adjetey.jpg",
  "abdul mumin": "/players/gha_abdul_mumin.jpg",
  "gideon mensah": "/players/gha_gideon_mensah.jpg",
  "baba rahman": "/players/gha_baba_rahman.jpg",
  "jerome opoku": "/players/gha_jerome_opoku.jpg",
  "kojo peprah oppong": "/players/gha_kojo_peprah_oppong.jpg",
  "derrick luckassen": "/players/gha_derrick_luckassen.jpg",
  "marvin senaya": "/players/gha_marvin_senaya.jpg",
  "caleb yirenkyi": "/players/gha_caleb_yirenkyi.jpg",
  "thomas partey": "/players/gha_thomas_partey.jpg",
  "kwasi sibo": "/players/gha_kwasi_sibo.jpg",
  "elisha owusu": "/players/gha_elisha_owusu.jpg",
  "augustine boakye": "/players/gha_augustine_boakye.jpg",
  "abdul fatawu": "/players/gha_abdul_fatawu.jpg",
  "christopher bonsu baah": "/players/gha_christopher_bonsu_baah.jpg",
  "inaki williams": "/players/gha_inaki_williams.jpg",
  "kamaldeen sulemana": "/players/gha_kamaldeen_sulemana.jpg",
  "ernest nuamah": "/players/gha_ernest_nuamah.jpg",
  "prince adu": "/players/gha_prince_adu.jpg",
  "johny placide": "/players/hai_johny_placide.jpg",
  "alexandre pierre": "/players/hai_alexandre_pierre.jpg",
  "josue duverger": "/players/hai_josue_duverger.jpg",
  "carlens arcus": "/players/hai_carlens_arcus.jpg",
  "keeto thermoncy": "/players/hai_keeto_thermoncy.jpg",
  "ricardo ade": "/players/hai_ricardo_ade.jpg",
  "hannes delcroix": "/players/hai_hannes_delcroix.jpg",
  "martin experience": "/players/hai_martin_experience.jpg",
  "markhus lacroix": "/players/hai_markhus_lacroix.jpg",
  "wilguens paugain": "/players/hai_wilguens_paugain.jpg",
  "carl sainte": "/players/hai_carl_sainte.jpg",
  "danley jean jacques": "/players/hai_danley_jean_jacques.jpg",
  "dominique simon": "/players/hai_dominique_simon.jpg",
  "woodensky pierre": "/players/hai_woodensky_pierre.jpg",
  "derrick etienne": "/players/hai_derrick_etienne.jpg",
  "duckens nazon": "/players/hai_duckens_nazon.jpg",
  "louicius deedson": "/players/hai_louicius_deedson.jpg",
  "ruben providence": "/players/hai_ruben_providence.jpg",
  "lenny joseph": "/players/hai_lenny_joseph.jpg",
  "wilson isidor": "/players/hai_wilson_isidor.jpg",
  "yassin fortune": "/players/hai_yassin_fortune.jpg",
  "frantzdy pierrot": "/players/hai_frantzdy_pierrot.jpg",
  "josue casimir": "/players/hai_josue_casimir.jpg",
  "alireza beiranvand": "/players/irn_alireza_beiranvand.jpg",
  "payam niazmand": "/players/irn_payam_niazmand.jpg",
  "hossein hosseini": "/players/irn_hossein_hosseini.jpg",
  "saleh hardani": "/players/irn_saleh_hardani.jpg",
  "ehsan hajisafi": "/players/irn_ehsan_hajisafi.jpg",
  "shoja khalilzadeh": "/players/irn_shoja_khalilzadeh.jpg",
  "milad mohammadi": "/players/irn_milad_mohammadi.jpg",
  "hossein kanani": "/players/irn_hossein_kanani.jpg",
  "arya yousefi": "/players/irn_arya_yousefi.jpg",
  "ali nemati": "/players/irn_ali_nemati.jpg",
  "ramin rezaeian": "/players/irn_ramin_rezaeian.jpg",
  "danial iri": "/players/irn_danial_iri.jpg",
  "saeid ezatolahi": "/players/irn_saeid_ezatolahi.jpg",
  "alireza jahanbakhsh": "/players/irn_alireza_jahanbakhsh.jpg",
  "mohammad mohebbi": "/players/irn_mohammad_mohebbi.jpg",
  "saman ghoddos": "/players/irn_saman_ghoddos.jpg",
  "roozbeh cheshmi": "/players/irn_roozbeh_cheshmi.jpg",
  "mehdi torabi": "/players/irn_mehdi_torabi.jpg",
  "mohammad ghorbani": "/players/irn_mohammad_ghorbani.jpg",
  "amirmohammad razaghinia": "/players/irn_amirmohammad_razaghinia.jpg",
  "mehdi taremi": "/players/irn_mehdi_taremi.jpg",
  "mehdi ghayedi": "/players/irn_mehdi_ghayedi.jpg",
  "ali alipour": "/players/irn_ali_alipour.jpg",
  "amirhossein hosseinzadeh": "/players/irn_amirhossein_hosseinzadeh.jpg",
  "shahriyar moghanloo": "/players/irn_shahriyar_moghanloo.jpg",
  "dennis dargahi": "/players/irn_dennis_dargahi.jpg",
  "fahad talib": "/players/irq_fahad_talib.jpg",
  "jalal hassan": "/players/irq_jalal_hassan.jpg",
  "ahmed basil": "/players/irq_ahmed_basil.jpg",
  "rebin sulaka": "/players/irq_rebin_sulaka.jpg",
  "hussein ali": "/players/irq_hussein_ali.jpg",
  "zaid tahseen": "/players/irq_zaid_tahseen.jpg",
  "akam hashim": "/players/irq_akam_hashim.jpg",
  "munaf younus": "/players/irq_munaf_younus.jpg",
  "ahmed maknazi": "/players/irq_ahmed_maknazi.jpg",
  "merchas doski": "/players/irq_merchas_doski.jpg",
  "mustafa saadoon": "/players/irq_mustafa_saadoon.jpg",
  "frans putros": "/players/irq_frans_putros.jpg",
  "youssef amyn": "/players/irq_youssef_amyn.jpg",
  "ibrahim bayesh": "/players/irq_ibrahim_bayesh.jpg",
  "zidane iqbal": "/players/irq_zidane_iqbal.jpg",
  "amir alammari": "/players/irq_amir_alammari.jpg",
  "kevin yakob": "/players/irq_kevin_yakob.jpg",
  "aimar sher": "/players/irq_aimar_sher.jpg",
  "zaid ismael": "/players/irq_zaid_ismael.jpg",
  "ali alhamadi": "/players/irq_ali_alhamadi.jpg",
  "mohanad ali": "/players/irq_mohanad_ali.jpg",
  "ahmed qasem": "/players/irq_ahmed_qasem.jpg",
  "ali yousif": "/players/irq_ali_yousif.jpg",
  "ali jasim": "/players/irq_ali_jasim.jpg",
  "aymen hussein": "/players/irq_aymen_hussein.jpg",
  "marko farji": "/players/irq_marko_farji.jpg",
  "zion suzuki": "/players/jpn_zion_suzuki.jpg",
  "keisuke osako": "/players/jpn_keisuke_osako.jpg",
  "tomoki hayakawa": "/players/jpn_tomoki_hayakawa.jpg",
  "yukinari sugawara": "/players/jpn_yukinari_sugawara.jpg",
  "shogo taniguchi": "/players/jpn_shogo_taniguchi.jpg",
  "kou itakura": "/players/jpn_kou_itakura.jpg",
  "yuto nagatomo": "/players/jpn_yuto_nagatomo.jpg",
  "tsuyoshi watanabe": "/players/jpn_tsuyoshi_watanabe.jpg",
  "ayumu seko": "/players/jpn_ayumu_seko.jpg",
  "hiroki ito": "/players/jpn_hiroki_ito.jpg",
  "takehiro tomiyasu": "/players/jpn_takehiro_tomiyasu.jpg",
  "junnosuke suzuki": "/players/jpn_junnosuke_suzuki.jpg",
  "ao tanaka": "/players/jpn_ao_tanaka.jpg",
  "ritsu doan": "/players/jpn_ritsu_doan.jpg",
  "daizen maeda": "/players/jpn_daizen_maeda.jpg",
  "keito nakamura": "/players/jpn_keito_nakamura.jpg",
  "junya ito": "/players/jpn_junya_ito.jpg",
  "daichi kamada": "/players/jpn_daichi_kamada.jpg",
  "yuito suzuki": "/players/jpn_yuito_suzuki.jpg",
  "kaishu sano": "/players/jpn_kaishu_sano.jpg",
  "shuto machino": "/players/jpn_shuto_machino.jpg",
  "ayase ueda": "/players/jpn_ayase_ueda.jpg",
  "koki ogawa": "/players/jpn_koki_ogawa.jpg",
  "kento shiogai": "/players/jpn_kento_shiogai.jpg",
  "yazeed abulaila": "/players/jor_yazeed_abulaila.jpg",
  "nour baniateyah": "/players/jor_nour_baniateyah.jpg",
  "abdallah alfakhori": "/players/jor_abdallah_alfakhori.jpg",
  "mohammad abuhasheesh": "/players/jor_mohammad_abuhasheesh.jpg",
  "abdallah nasib": "/players/jor_abdallah_nasib.jpg",
  "yazan alarab": "/players/jor_yazan_alarab.jpg",
  "mohammad abualnadi": "/players/jor_mohammad_abualnadi.jpg",
  "saleem obaid": "/players/jor_saleem_obaid.jpg",
  "saed alrosan": "/players/jor_saed_alrosan.jpg",
  "ehsan haddad": "/players/jor_ehsan_haddad.jpg",
  "anas badawi": "/players/jor_anas_badawi.jpg",
  "amer jamous": "/players/jor_amer_jamous.jpg",
  "noor alrawabdeh": "/players/jor_noor_alrawabdeh.jpg",
  "rajaei ayed": "/players/jor_rajaei_ayed.jpg",
  "ibrahim sadeh": "/players/jor_ibrahim_sadeh.jpg",
  "mohammad abughoush": "/players/jor_mohammad_abughoush.jpg",
  "mohannad abutaha": "/players/jor_mohannad_abutaha.jpg",
  "nizar alrashdan": "/players/jor_nizar_alrashdan.jpg",
  "mohammad aldaoud": "/players/jor_mohammad_aldaoud.jpg",
  "mohammad abuzraiq": "/players/jor_mohammad_abuzraiq.jpg",
  "ali olwan": "/players/jor_ali_olwan.jpg",
  "odeh fakhoury": "/players/jor_odeh_fakhoury.jpg",
  "mahmoud almardi": "/players/jor_mahmoud_almardi.jpg",
  "ali azaizeh": "/players/jor_ali_azaizeh.jpg",
  "kim seunggyu": "/players/kor_kim_seunggyu.jpg",
  "song bumkeun": "/players/kor_song_bumkeun.jpg",
  "jo hyeonwoo": "/players/kor_jo_hyeonwoo.jpg",
  "lee hanbeom": "/players/kor_lee_hanbeom.jpg",
  "kim minjae": "/players/kor_kim_minjae.jpg",
  "kim taehyeon": "/players/kor_kim_taehyeon.jpg",
  "lee taeseok": "/players/kor_lee_taeseok.jpg",
  "cho wije": "/players/kor_cho_wije.jpg",
  "kim moonhwan": "/players/kor_kim_moonhwan.jpg",
  "park jinseob": "/players/kor_park_jinseob.jpg",
  "seol youngwoo": "/players/kor_seol_youngwoo.jpg",
  "castrop jens": "/players/kor_castrop_jens.jpg",
  "lee gihyuk": "/players/kor_lee_gihyuk.jpg",
  "hwang inbeom": "/players/kor_hwang_inbeom.jpg",
  "paik seungho": "/players/kor_paik_seungho.jpg",
  "lee jaesung": "/players/kor_lee_jaesung.jpg",
  "hwang heechan": "/players/kor_hwang_heechan.jpg",
  "bae junho": "/players/kor_bae_junho.jpg",
  "lee kangin": "/players/kor_lee_kangin.jpg",
  "yang hyunjun": "/players/kor_yang_hyunjun.jpg",
  "kim jingyu": "/players/kor_kim_jingyu.jpg",
  "eom jisung": "/players/kor_eom_jisung.jpg",
  "lee donggyeong": "/players/kor_lee_donggyeong.jpg",
  "son heungmin": "/players/kor_son_heungmin.jpg",
  "cho guesung": "/players/kor_cho_guesung.jpg",
  "oh hyeongyu": "/players/kor_oh_hyeongyu.jpg",
  "yassine bounou": "/players/mar_yassine_bounou.jpg",
  "munir el kajoui": "/players/mar_munir_el_kajoui.jpg",
  "ahmed reda tagnaouti": "/players/mar_ahmed_reda_tagnaouti.jpg",
  "achraf hakimi": "/players/mar_achraf_hakimi.jpg",
  "noussair mazraoui": "/players/mar_noussair_mazraoui.jpg",
  "marwane saadane": "/players/mar_marwane_saadane.jpg",
  "zakaria el ouahdi": "/players/mar_zakaria_el_ouahdi.jpg",
  "issa diop": "/players/mar_issa_diop.jpg",
  "chadi riad": "/players/mar_chadi_riad.jpg",
  "youssef belammari": "/players/mar_youssef_belammari.jpg",
  "redouane halhal": "/players/mar_redouane_halhal.jpg",
  "anass salah eddine": "/players/mar_anass_salah_eddine.jpg",
  "sofyan amrabat": "/players/mar_sofyan_amrabat.jpg",
  "ayyoub bouaddi": "/players/mar_ayyoub_bouaddi.jpg",
  "chemsdine talbi": "/players/mar_chemsdine_talbi.jpg",
  "azzedine ounahi": "/players/mar_azzedine_ounahi.jpg",
  "ismael saibari": "/players/mar_ismael_saibari.jpg",
  "samir el mourabet": "/players/mar_samir_el_mourabet.jpg",
  "gessime yassine": "/players/mar_gessime_yassine.jpg",
  "bilal el khannouss": "/players/mar_bilal_el_khannouss.jpg",
  "neil el aynaoui": "/players/mar_neil_el_aynaoui.jpg",
  "soufiane rahimi": "/players/mar_soufiane_rahimi.jpg",
  "brahim diaz": "/players/mar_brahim_diaz.jpg",
  "amine sbai": "/players/mar_amine_sbai.jpg",
  "ayoub el kaabi": "/players/mar_ayoub_el_kaabi.jpg",
  "ayoube amaimouni": "/players/mar_ayoube_amaimouni.jpg",
  "raul rangel": "/players/mex_raul_rangel.jpg",
  "carlos acevedo": "/players/mex_carlos_acevedo.jpg",
  "guillermo ochoa": "/players/mex_guillermo_ochoa.jpg",
  "jorge sanchez": "/players/mex_jorge_sanchez.jpg",
  "cesar montes": "/players/mex_cesar_montes.jpg",
  "edson alvarez": "/players/mex_edson_alvarez.jpg",
  "johan vasquez": "/players/mex_johan_vasquez.jpg",
  "israel reyes": "/players/mex_israel_reyes.jpg",
  "mateo chavez": "/players/mex_mateo_chavez.jpg",
  "jesus gallardo": "/players/mex_jesus_gallardo.jpg",
  "erik lira": "/players/mex_erik_lira.jpg",
  "luis romo": "/players/mex_luis_romo.jpg",
  "alvaro fidalgo": "/players/mex_alvaro_fidalgo.jpg",
  "orbelin pineda": "/players/mex_orbelin_pineda.jpg",
  "obed vargas": "/players/mex_obed_vargas.jpg",
  "gilberto mora": "/players/mex_gilberto_mora.jpg",
  "luis chavez": "/players/mex_luis_chavez.jpg",
  "brian gutierrez": "/players/mex_brian_gutierrez.jpg",
  "raul jimenez": "/players/mex_raul_jimenez.jpg",
  "alexis vega": "/players/mex_alexis_vega.jpg",
  "santiago gimenez": "/players/mex_santiago_gimenez.jpg",
  "armando gonzalez": "/players/mex_armando_gonzalez.jpg",
  "julian quinones": "/players/mex_julian_quinones.jpg",
  "cesar huerta": "/players/mex_cesar_huerta.jpg",
  "guillermo martinez": "/players/mex_guillermo_martinez.jpg",
  "roberto alvarado": "/players/mex_roberto_alvarado.jpg",
  "bart verbruggen": "/players/ned_bart_verbruggen.jpg",
  "robin roefs": "/players/ned_robin_roefs.jpg",
  "mark flekken": "/players/ned_mark_flekken.jpg",
  "lutsharel geertruida": "/players/ned_lutsharel_geertruida.jpg",
  "virgil van dijk": "/players/ned_virgil_van_dijk.jpg",
  "nathan ake": "/players/ned_nathan_ake.jpg",
  "jan paul van hecke": "/players/ned_jan_paul_van_hecke.jpg",
  "mats wieffer": "/players/ned_mats_wieffer.jpg",
  "micky van de ven": "/players/ned_micky_van_de_ven.jpg",
  "denzel dumfries": "/players/ned_denzel_dumfries.jpg",
  "jorrel hato": "/players/ned_jorrel_hato.jpg",
  "marten de roon": "/players/ned_marten_de_roon.jpg",
  "justin kluivert": "/players/ned_justin_kluivert.jpg",
  "ryan gravenberch": "/players/ned_ryan_gravenberch.jpg",
  "tijjani reijnders": "/players/ned_tijjani_reijnders.jpg",
  "guus til": "/players/ned_guus_til.jpg",
  "teun koopmeiners": "/players/ned_teun_koopmeiners.jpg",
  "frenkie de jong": "/players/ned_frenkie_de_jong.jpg",
  "quinten timber": "/players/ned_quinten_timber.jpg",
  "wout weghorst": "/players/ned_wout_weghorst.jpg",
  "memphis depay": "/players/ned_memphis_depay.jpg",
  "cody gakpo": "/players/ned_cody_gakpo.jpg",
  "noa lang": "/players/ned_noa_lang.jpg",
  "donyell malen": "/players/ned_donyell_malen.jpg",
  "brian brobbey": "/players/ned_brian_brobbey.jpg",
  "crysencio summerville": "/players/ned_crysencio_summerville.jpg",
  "max crocombe": "/players/nzl_max_crocombe.jpg",
  "alex paulsen": "/players/nzl_alex_paulsen.jpg",
  "michael woud": "/players/nzl_michael_woud.jpg",
  "tim payne": "/players/nzl_tim_payne.jpg",
  "francis de vries": "/players/nzl_francis_de_vries.jpg",
  "tyler bindon": "/players/nzl_tyler_bindon.jpg",
  "michael boxall": "/players/nzl_michael_boxall.jpg",
  "liberato cacace": "/players/nzl_liberato_cacace.jpg",
  "nando pijnaker": "/players/nzl_nando_pijnaker.jpg",
  "finn surman": "/players/nzl_finn_surman.jpg",
  "callan elliot": "/players/nzl_callan_elliot.jpg",
  "tommy smith": "/players/nzl_tommy_smith.jpg",
  "joe bell": "/players/nzl_joe_bell.jpg",
  "marko stamenic": "/players/nzl_marko_stamenic.jpg",
  "sarpreet singh": "/players/nzl_sarpreet_singh.jpg",
  "elijah just": "/players/nzl_elijah_just.jpg",
  "alex rufer": "/players/nzl_alex_rufer.jpg",
  "ben old": "/players/nzl_ben_old.jpg",
  "callum mccowatt": "/players/nzl_callum_mccowatt.jpg",
  "ryan thomas": "/players/nzl_ryan_thomas.jpg",
  "lachlan bayliss": "/players/nzl_lachlan_bayliss.jpg",
  "logan rogerson": "/players/nzl_logan_rogerson.jpg",
  "chris wood": "/players/nzl_chris_wood.jpg",
  "kosta barbarouses": "/players/nzl_kosta_barbarouses.jpg",
  "ben waine": "/players/nzl_ben_waine.jpg",
  "jesse randall": "/players/nzl_jesse_randall.jpg",
  "orjan nyland": "/players/nor_orjan_nyland.jpg",
  "sander tangvik": "/players/nor_sander_tangvik.jpg",
  "egil selvik": "/players/nor_egil_selvik.jpg",
  "kristoffer ajer": "/players/nor_kristoffer_ajer.jpg",
  "leo ostigard": "/players/nor_leo_ostigard.jpg",
  "david moller wolfe": "/players/nor_david_moller_wolfe.jpg",
  "fredrik andre bjorkan": "/players/nor_fredrik_andre_bjorkan.jpg",
  "marcus holmgren pedersen": "/players/nor_marcus_holmgren_pedersen.jpg",
  "torbjorn heggem": "/players/nor_torbjorn_heggem.jpg",
  "sondre langas": "/players/nor_sondre_langas.jpg",
  "henrik falchener": "/players/nor_henrik_falchener.jpg",
  "morten thorsby": "/players/nor_morten_thorsby.jpg",
  "patrick berg": "/players/nor_patrick_berg.jpg",
  "sander berge": "/players/nor_sander_berge.jpg",
  "martin odegaard": "/players/nor_martin_odegaard.jpg",
  "fredrik aursnes": "/players/nor_fredrik_aursnes.jpg",
  "kristian thorstvedt": "/players/nor_kristian_thorstvedt.jpg",
  "thelo aasgaard": "/players/nor_thelo_aasgaard.jpg",
  "andreas schjelderup": "/players/nor_andreas_schjelderup.jpg",
  "oscar bobb": "/players/nor_oscar_bobb.jpg",
  "jens petter hauge": "/players/nor_jens_petter_hauge.jpg",
  "alexander sorloth": "/players/nor_alexander_sorloth.jpg",
  "erling haaland": "/players/nor_erling_haaland.jpg",
  "jorgen strand larsen": "/players/nor_jorgen_strand_larsen.jpg",
  "julian ryerson": "/players/nor_julian_ryerson.jpg",
  "luis mejia": "/players/pan_luis_mejia.jpg",
  "cesar samudio": "/players/pan_cesar_samudio.jpg",
  "orlando mosquera": "/players/pan_orlando_mosquera.jpg",
  "cesar blackman": "/players/pan_cesar_blackman.jpg",
  "jose cordoba": "/players/pan_jose_cordoba.jpg",
  "fidel escobar": "/players/pan_fidel_escobar.jpg",
  "edgardo farina": "/players/pan_edgardo_farina.jpg",
  "jiovany ramos": "/players/pan_jiovany_ramos.jpg",
  "carlos harvey": "/players/pan_carlos_harvey.jpg",
  "eric davis": "/players/pan_eric_davis.jpg",
  "andres andrade": "/players/pan_andres_andrade.jpg",
  "amir murillo": "/players/pan_amir_murillo.jpg",
  "roderick miller": "/players/pan_roderick_miller.jpg",
  "jorge gutierrez": "/players/pan_jorge_gutierrez.jpg",
  "cristian martinez": "/players/pan_cristian_martinez.jpg",
  "jose luis rodriguez": "/players/pan_jose_luis_rodriguez.jpg",
  "adalberto carrasquilla": "/players/pan_adalberto_carrasquilla.jpg",
  "ismael diaz": "/players/pan_ismael_diaz.jpg",
  "edgar yoel barcenas": "/players/pan_edgar_yoel_barcenas.jpg",
  "alberto quintero": "/players/pan_alberto_quintero.jpg",
  "anibal godoy": "/players/pan_anibal_godoy.jpg",
  "cesar yanis": "/players/pan_cesar_yanis.jpg",
  "tomas rodriguez": "/players/pan_tomas_rodriguez.jpg",
  "jose fajardo": "/players/pan_jose_fajardo.jpg",
  "cecilio waterman": "/players/pan_cecilio_waterman.jpg",
  "azarias londono": "/players/pan_azarias_londono.jpg",
  "gatito fernandez": "/players/par_gatito_fernandez.jpg",
  "orlando gill": "/players/par_orlando_gill.jpg",
  "gaston olveira": "/players/par_gaston_olveira.jpg",
  "gustavo velazquez": "/players/par_gustavo_velazquez.jpg",
  "omar alderete": "/players/par_omar_alderete.jpg",
  "juan jose caceres": "/players/par_juan_jose_caceres.jpg",
  "fabian balbuena": "/players/par_fabian_balbuena.jpg",
  "junior alonso": "/players/par_junior_alonso.jpg",
  "jose canale": "/players/par_jose_canale.jpg",
  "gustavo gomez": "/players/par_gustavo_gomez.jpg",
  "alexandro maidana": "/players/par_alexandro_maidana.jpg",
  "ramon sosa": "/players/par_ramon_sosa.jpg",
  "diego gomez": "/players/par_diego_gomez.jpg",
  "miguel almiron": "/players/par_miguel_almiron.jpg",
  "mauricio": "/players/par_mauricio.jpg",
  "andres cubas": "/players/par_andres_cubas.jpg",
  "damian bobadilla": "/players/par_damian_bobadilla.jpg",
  "braian ojeda": "/players/par_braian_ojeda.jpg",
  "matias galarza": "/players/par_matias_galarza.jpg",
  "gustavo caballero": "/players/par_gustavo_caballero.jpg",
  "antonio sanabria": "/players/par_antonio_sanabria.jpg",
  "alejandro romero gamarra": "/players/par_alejandro_romero_gamarra.jpg",
  "alex arce": "/players/par_alex_arce.jpg",
  "julio enciso": "/players/par_julio_enciso.jpg",
  "gabriel avalos": "/players/par_gabriel_avalos.jpg",
  "isidro pitta": "/players/par_isidro_pitta.jpg",
  "diogo costa": "/players/por_diogo_costa.jpg",
  "jose sa": "/players/por_jose_sa.jpg",
  "rui silva": "/players/por_rui_silva.jpg",
  "nelson semedo": "/players/por_nelson_semedo.jpg",
  "ruben dias": "/players/por_ruben_dias.jpg",
  "tomas araujo": "/players/por_tomas_araujo.jpg",
  "diogo dalot": "/players/por_diogo_dalot.jpg",
  "renato veiga": "/players/por_renato_veiga.jpg",
  "goncalo inacio": "/players/por_goncalo_inacio.jpg",
  "joao cancelo": "/players/por_joao_cancelo.jpg",
  "samu costa": "/players/por_samu_costa.jpg",
  "nuno mendes": "/players/por_nuno_mendes.jpg",
  "matheus nunes": "/players/por_matheus_nunes.jpg",
  "bruno fernandes": "/players/por_bruno_fernandes.jpg",
  "bernardo silva": "/players/por_bernardo_silva.jpg",
  "joao neves": "/players/por_joao_neves.jpg",
  "ruben neves": "/players/por_ruben_neves.jpg",
  "vitinha": "/players/por_vitinha.jpg",
  "cristiano ronaldo": "/players/por_cristiano_ronaldo.jpg",
  "goncalo ramos": "/players/por_goncalo_ramos.jpg",
  "joao felix": "/players/por_joao_felix.jpg",
  "francisco trincao": "/players/por_francisco_trincao.jpg",
  "rafael leao": "/players/por_rafael_leao.jpg",
  "pedro neto": "/players/por_pedro_neto.jpg",
  "goncalo guedes": "/players/por_goncalo_guedes.jpg",
  "francisco conceicao": "/players/por_francisco_conceicao.jpg",
  "mahmoud abunada": "/players/qat_mahmoud_abunada.jpg",
  "salah zakaria": "/players/qat_salah_zakaria.jpg",
  "meshaal barsham": "/players/qat_meshaal_barsham.jpg",
  "pedro miguel": "/players/qat_pedro_miguel.jpg",
  "lucas mendes": "/players/qat_lucas_mendes.jpg",
  "issa laye": "/players/qat_issa_laye.jpg",
  "jassem gaber": "/players/qat_jassem_gaber.jpg",
  "ayoub aloui": "/players/qat_ayoub_aloui.jpg",
  "homam ahmed": "/players/qat_homam_ahmed.jpg",
  "boualem khoukhi": "/players/qat_boualem_khoukhi.jpg",
  "sultan albrake": "/players/qat_sultan_albrake.jpg",
  "alhashmi alhussein": "/players/qat_alhashmi_alhussein.jpg",
  "abdulaziz hatem": "/players/qat_abdulaziz_hatem.jpg",
  "karim boudiaf": "/players/qat_karim_boudiaf.jpg",
  "ahmed alganehi": "/players/qat_ahmed_alganehi.jpg",
  "ahmed fathy": "/players/qat_ahmed_fathy.jpg",
  "assim madibo": "/players/qat_assim_madibo.jpg",
  "ahmed alaaeldin": "/players/qat_ahmed_alaaeldin.jpg",
  "edmilson junior": "/players/qat_edmilson_junior.jpg",
  "mohammed muntari": "/players/qat_mohammed_muntari.jpg",
  "hassan alhaydos": "/players/qat_hassan_alhaydos.jpg",
  "akram afif": "/players/qat_akram_afif.jpg",
  "yusuf abdurisag": "/players/qat_yusuf_abdurisag.jpg",
  "almoez ali": "/players/qat_almoez_ali.jpg",
  "tahsin mohammed": "/players/qat_tahsin_mohammed.jpg",
  "mohamed manai": "/players/qat_mohamed_manai.jpg",
  "nawaf alaqidi": "/players/ksa_nawaf_alaqidi.jpg",
  "mohammed alowais": "/players/ksa_mohammed_alowais.jpg",
  "ahmed alkassar": "/players/ksa_ahmed_alkassar.jpg",
  "ali majrashi": "/players/ksa_ali_majrashi.jpg",
  "ali lajami": "/players/ksa_ali_lajami.jpg",
  "abdulelah alamri": "/players/ksa_abdulelah_alamri.jpg",
  "hassan altambakti": "/players/ksa_hassan_altambakti.jpg",
  "saud abdulhamid": "/players/ksa_saud_abdulhamid.jpg",
  "nawaf bu washl": "/players/ksa_nawaf_bu_washl.jpg",
  "hassan kadish": "/players/ksa_hassan_kadish.jpg",
  "moteb alharbi": "/players/ksa_moteb_alharbi.jpg",
  "jehad thikri": "/players/ksa_jehad_thikri.jpg",
  "mohammed abu alshamat": "/players/ksa_mohammed_abu_alshamat.jpg",
  "nasser aldawsari": "/players/ksa_nasser_aldawsari.jpg",
  "abdullah alkhaibari": "/players/ksa_abdullah_alkhaibari.jpg",
  "ziyad aljohani": "/players/ksa_ziyad_aljohani.jpg",
  "ala alhajji": "/players/ksa_ala_alhajji.jpg",
  "mohamed kanno": "/players/ksa_mohamed_kanno.jpg",
  "aiman yahya": "/players/ksa_aiman_yahya.jpg",
  "feras albrikan": "/players/ksa_feras_albrikan.jpg",
  "salem aldawsari": "/players/ksa_salem_aldawsari.jpg",
  "saleh alshehri": "/players/ksa_saleh_alshehri.jpg",
  "khalid alghannam": "/players/ksa_khalid_alghannam.jpg",
  "abdullah alhamddan": "/players/ksa_abdullah_alhamddan.jpg",
  "sultan mandash": "/players/ksa_sultan_mandash.jpg",
  "angus gunn": "/players/sco_angus_gunn.jpg",
  "liam kelly": "/players/sco_liam_kelly.jpg",
  "craig gordon": "/players/sco_craig_gordon.jpg",
  "aaron hickey": "/players/sco_aaron_hickey.jpg",
  "andy robertson": "/players/sco_andy_robertson.jpg",
  "grant hanley": "/players/sco_grant_hanley.jpg",
  "kieran tierney": "/players/sco_kieran_tierney.jpg",
  "jack hendry": "/players/sco_jack_hendry.jpg",
  "john souttar": "/players/sco_john_souttar.jpg",
  "dominic hyam": "/players/sco_dominic_hyam.jpg",
  "nathan patterson": "/players/sco_nathan_patterson.jpg",
  "anthony ralston": "/players/sco_anthony_ralston.jpg",
  "scott mckenna": "/players/sco_scott_mckenna.jpg",
  "scott mctominay": "/players/sco_scott_mctominay.jpg",
  "john mcginn": "/players/sco_john_mcginn.jpg",
  "tyler fletcher": "/players/sco_tyler_fletcher.jpg",
  "ryan christie": "/players/sco_ryan_christie.jpg",
  "lewis ferguson": "/players/sco_lewis_ferguson.jpg",
  "kenny mclean": "/players/sco_kenny_mclean.jpg",
  "lyndon dykes": "/players/sco_lyndon_dykes.jpg",
  "che adams": "/players/sco_che_adams.jpg",
  "ross stewart": "/players/sco_ross_stewart.jpg",
  "george hirst": "/players/sco_george_hirst.jpg",
  "lawrence shankland": "/players/sco_lawrence_shankland.jpg",
  "findlay curtis": "/players/sco_findlay_curtis.jpg",
  "yehvann diouf": "/players/sen_yehvann_diouf.jpg",
  "edouard mendy": "/players/sen_edouard_mendy.jpg",
  "mory diaw": "/players/sen_mory_diaw.jpg",
  "mamadou sarr": "/players/sen_mamadou_sarr.jpg",
  "kalidou koulibaly": "/players/sen_kalidou_koulibaly.jpg",
  "abdoulaye seck": "/players/sen_abdoulaye_seck.jpg",
  "ismail jakobs": "/players/sen_ismail_jakobs.jpg",
  "krepin diatta": "/players/sen_krepin_diatta.jpg",
  "moussa niakhate": "/players/sen_moussa_niakhate.jpg",
  "antoine mendy": "/players/sen_antoine_mendy.jpg",
  "el hadji malick diouf": "/players/sen_el_hadji_malick_diouf.jpg",
  "idrissa gana gueye": "/players/sen_idrissa_gana_gueye.jpg",
  "pathe ciss": "/players/sen_pathe_ciss.jpg",
  "lamine camara": "/players/sen_lamine_camara.jpg",
  "pape matar sarr": "/players/sen_pape_matar_sarr.jpg",
  "habib diarra": "/players/sen_habib_diarra.jpg",
  "bara sapoko ndiaye": "/players/sen_bara_sapoko_ndiaye.jpg",
  "pape gueye": "/players/sen_pape_gueye.jpg",
  "assane diao": "/players/sen_assane_diao.jpg",
  "bamba dieng": "/players/sen_bamba_dieng.jpg",
  "sadio mane": "/players/sen_sadio_mane.jpg",
  "nicolas jackson": "/players/sen_nicolas_jackson.jpg",
  "cherif ndiaye": "/players/sen_cherif_ndiaye.jpg",
  "iliman ndiaye": "/players/sen_iliman_ndiaye.jpg",
  "ismaila sarr": "/players/sen_ismaila_sarr.jpg",
  "ibrahim mbaye": "/players/sen_ibrahim_mbaye.jpg",
  "ronwen williams": "/players/rsa_ronwen_williams.jpg",
  "sipho chaine": "/players/rsa_sipho_chaine.jpg",
  "ricardo goss": "/players/rsa_ricardo_goss.jpg",
  "thabang matuludi": "/players/rsa_thabang_matuludi.jpg",
  "khulumani ndamane": "/players/rsa_khulumani_ndamane.jpg",
  "aubrey modiba": "/players/rsa_aubrey_modiba.jpg",
  "mbekezeli mbokazi": "/players/rsa_mbekezeli_mbokazi.jpg",
  "samukele kabini": "/players/rsa_samukele_kabini.jpg",
  "nkosinathi sibisi": "/players/rsa_nkosinathi_sibisi.jpg",
  "khuliso mudau": "/players/rsa_khuliso_mudau.jpg",
  "ime okon": "/players/rsa_ime_okon.jpg",
  "olwethu makhanya": "/players/rsa_olwethu_makhanya.jpg",
  "bradley cross": "/players/rsa_bradley_cross.jpg",
  "teboho mokoena": "/players/rsa_teboho_mokoena.jpg",
  "thalente mbatha": "/players/rsa_thalente_mbatha.jpg",
  "themba zwane": "/players/rsa_themba_zwane.jpg",
  "sphephelo sithole": "/players/rsa_sphephelo_sithole.jpg",
  "jayden adams": "/players/rsa_jayden_adams.jpg",
  "oswin appollis": "/players/rsa_oswin_appollis.jpg",
  "tshepang moremi": "/players/rsa_tshepang_moremi.jpg",
  "lyle foster": "/players/rsa_lyle_foster.jpg",
  "relebohile mofokeng": "/players/rsa_relebohile_mofokeng.jpg",
  "thapelo maseko": "/players/rsa_thapelo_maseko.jpg",
  "iqraam rayners": "/players/rsa_iqraam_rayners.jpg",
  "evidence makgopa": "/players/rsa_evidence_makgopa.jpg",
  "kamogelo sebelebele": "/players/rsa_kamogelo_sebelebele.jpg",
  "david raya": "/players/esp_david_raya.jpg",
  "joan garcia": "/players/esp_joan_garcia.jpg",
  "unai simon": "/players/esp_unai_simon.jpg",
  "marc pubill": "/players/esp_marc_pubill.jpg",
  "alex grimaldo": "/players/esp_alex_grimaldo.jpg",
  "eric garcia": "/players/esp_eric_garcia.jpg",
  "marcos llorente": "/players/esp_marcos_llorente.jpg",
  "pedro porro": "/players/esp_pedro_porro.jpg",
  "aymeric laporte": "/players/esp_aymeric_laporte.jpg",
  "pau cubarsi": "/players/esp_pau_cubarsi.jpg",
  "marc cucurella": "/players/esp_marc_cucurella.jpg",
  "mikel merino": "/players/esp_mikel_merino.jpg",
  "fabian ruiz": "/players/esp_fabian_ruiz.jpg",
  "gavi": "/players/esp_gavi.jpg",
  "alex baena": "/players/esp_alex_baena.jpg",
  "rodri": "/players/esp_rodri.jpg",
  "martin zubimendi": "/players/esp_martin_zubimendi.jpg",
  "pedri": "/players/esp_pedri.jpg",
  "ferran torres": "/players/esp_ferran_torres.jpg",
  "dani olmo": "/players/esp_dani_olmo.jpg",
  "yeremy pino": "/players/esp_yeremy_pino.jpg",
  "nico williams": "/players/esp_nico_williams.jpg",
  "lamine yamal": "/players/esp_lamine_yamal.jpg",
  "mikel oyarzabal": "/players/esp_mikel_oyarzabal.jpg",
  "victor munoz": "/players/esp_victor_munoz.jpg",
  "borja iglesias": "/players/esp_borja_iglesias.jpg",
  "jacob widell zetterstrom": "/players/swe_jacob_widell_zetterstrom.jpg",
  "viktor johansson": "/players/swe_viktor_johansson.jpg",
  "kristoffer nordfeldt": "/players/swe_kristoffer_nordfeldt.jpg",
  "gustaf lagerbielke": "/players/swe_gustaf_lagerbielke.jpg",
  "victor lindelof": "/players/swe_victor_lindelof.jpg",
  "isak hien": "/players/swe_isak_hien.jpg",
  "gabriel gudmundsson": "/players/swe_gabriel_gudmundsson.jpg",
  "herman johansson": "/players/swe_herman_johansson.jpg",
  "daniel svensson": "/players/swe_daniel_svensson.jpg",
  "hjalmar ekdal": "/players/swe_hjalmar_ekdal.jpg",
  "carl starfelt": "/players/swe_carl_starfelt.jpg",
  "eric smith": "/players/swe_eric_smith.jpg",
  "alexander bernhardsson": "/players/swe_alexander_bernhardsson.jpg",
  "elliot stroud": "/players/swe_elliot_stroud.jpg",
  "lucas bergvall": "/players/swe_lucas_bergvall.jpg",
  "benjamin nygren": "/players/swe_benjamin_nygren.jpg",
  "ken sema": "/players/swe_ken_sema.jpg",
  "jesper karlstrom": "/players/swe_jesper_karlstrom.jpg",
  "yasin ayari": "/players/swe_yasin_ayari.jpg",
  "mattias svanberg": "/players/swe_mattias_svanberg.jpg",
  "besfort zeneli": "/players/swe_besfort_zeneli.jpg",
  "alexander isak": "/players/swe_alexander_isak.jpg",
  "anthony elanga": "/players/swe_anthony_elanga.jpg",
  "viktor gyokeres": "/players/swe_viktor_gyokeres.jpg",
  "gustaf nilsson": "/players/swe_gustaf_nilsson.jpg",
  "taha ali": "/players/swe_taha_ali.jpg",
  "gregor kobel": "/players/sui_gregor_kobel.jpg",
  "yvon mvogo": "/players/sui_yvon_mvogo.jpg",
  "marvin keller": "/players/sui_marvin_keller.jpg",
  "miro muheim": "/players/sui_miro_muheim.jpg",
  "silvan widmer": "/players/sui_silvan_widmer.jpg",
  "nico elvedi": "/players/sui_nico_elvedi.jpg",
  "manuel akanji": "/players/sui_manuel_akanji.jpg",
  "ricardo rodriguez": "/players/sui_ricardo_rodriguez.jpg",
  "eray coemert": "/players/sui_eray_coemert.jpg",
  "aurele amenda": "/players/sui_aurele_amenda.jpg",
  "luca jaquez": "/players/sui_luca_jaquez.jpg",
  "denis zakaria": "/players/sui_denis_zakaria.jpg",
  "remo freuler": "/players/sui_remo_freuler.jpg",
  "johan manzambi": "/players/sui_johan_manzambi.jpg",
  "granit xhaka": "/players/sui_granit_xhaka.jpg",
  "ardon jashari": "/players/sui_ardon_jashari.jpg",
  "djibril sow": "/players/sui_djibril_sow.jpg",
  "michel aebischer": "/players/sui_michel_aebischer.jpg",
  "fabian rieder": "/players/sui_fabian_rieder.jpg",
  "breel embolo": "/players/sui_breel_embolo.jpg",
  "dan ndoye": "/players/sui_dan_ndoye.jpg",
  "christian fassnacht": "/players/sui_christian_fassnacht.jpg",
  "ruben vargas": "/players/sui_ruben_vargas.jpg",
  "noah okafor": "/players/sui_noah_okafor.jpg",
  "zeki amdouni": "/players/sui_zeki_amdouni.jpg",
  "cedric itten": "/players/sui_cedric_itten.jpg",
  "mouhib chamakh": "/players/tun_mouhib_chamakh.jpg",
  "aymen dahmen": "/players/tun_aymen_dahmen.jpg",
  "sabri ben hessen": "/players/tun_sabri_ben_hessen.jpg",
  "ali abdi": "/players/tun_ali_abdi.jpg",
  "montassar talbi": "/players/tun_montassar_talbi.jpg",
  "omar rekik": "/players/tun_omar_rekik.jpg",
  "adam arous": "/players/tun_adam_arous.jpg",
  "dylan bronn": "/players/tun_dylan_bronn.jpg",
  "mortadha ben ouanes": "/players/tun_mortadha_ben_ouanes.jpg",
  "yan valery": "/players/tun_yan_valery.jpg",
  "mohamed amine ben hmida": "/players/tun_mohamed_amine_ben_hmida.jpg",
  "moutaz neffati": "/players/tun_moutaz_neffati.jpg",
  "raed chikhaoui": "/players/tun_raed_chikhaoui.jpg",
  "hannibal mejbri": "/players/tun_hannibal_mejbri.jpg",
  "ismael gharbi": "/players/tun_ismael_gharbi.jpg",
  "rani khedira": "/players/tun_rani_khedira.jpg",
  "khalil ayari": "/players/tun_khalil_ayari.jpg",
  "mohamed hadj mahmoud": "/players/tun_mohamed_hadj_mahmoud.jpg",
  "ellyes skhiri": "/players/tun_ellyes_skhiri.jpg",
  "anis slimane": "/players/tun_anis_slimane.jpg",
  "sebastian tounekti": "/players/tun_sebastian_tounekti.jpg",
  "elias achouri": "/players/tun_elias_achouri.jpg",
  "elias saad": "/players/tun_elias_saad.jpg",
  "hazem mastouri": "/players/tun_hazem_mastouri.jpg",
  "rayan elloumi": "/players/tun_rayan_elloumi.jpg",
  "firas chaouat": "/players/tun_firas_chaouat.jpg",
  "mert gunok": "/players/tur_mert_gunok.jpg",
  "altay bayindir": "/players/tur_altay_bayindir.jpg",
  "ugurcan cakir": "/players/tur_ugurcan_cakir.jpg",
  "zeki celik": "/players/tur_zeki_celik.jpg",
  "merih demiral": "/players/tur_merih_demiral.jpg",
  "caglar soyuncu": "/players/tur_caglar_soyuncu.jpg",
  "eren elmali": "/players/tur_eren_elmali.jpg",
  "abdulkerim bardakci": "/players/tur_abdulkerim_bardakci.jpg",
  "ozan kabak": "/players/tur_ozan_kabak.jpg",
  "mert muldur": "/players/tur_mert_muldur.jpg",
  "ferdi kadioglu": "/players/tur_ferdi_kadioglu.jpg",
  "samet akaydin": "/players/tur_samet_akaydin.jpg",
  "orkun kokcu": "/players/tur_orkun_kokcu.jpg",
  "hakan calhanoglu": "/players/tur_hakan_calhanoglu.jpg",
  "ismail yuksek": "/players/tur_ismail_yuksek.jpg",
  "kaan ayhan": "/players/tur_kaan_ayhan.jpg",
  "kerem akturkoglu": "/players/tur_kerem_akturkoglu.jpg",
  "arda guler": "/players/tur_arda_guler.jpg",
  "deniz gul": "/players/tur_deniz_gul.jpg",
  "kenan yildiz": "/players/tur_kenan_yildiz.jpg",
  "irfan can kahveci": "/players/tur_irfan_can_kahveci.jpg",
  "yunus akgun": "/players/tur_yunus_akgun.jpg",
  "baris alper yilmaz": "/players/tur_baris_alper_yilmaz.jpg",
  "oguz aydin": "/players/tur_oguz_aydin.jpg",
  "can uzun": "/players/tur_can_uzun.jpg",
  "matt turner": "/players/usa_matt_turner.jpg",


  "matt freese": "/players/usa_matt_freese.jpg",
  "chris brady": "/players/usa_chris_brady.jpg",
  "sergino dest": "/players/usa_sergino_dest.jpg",
  "chris richards": "/players/usa_chris_richards.jpg",
  "antonee robinson": "/players/usa_antonee_robinson.jpg",
  "auston trusty": "/players/usa_auston_trusty.jpg",
  "miles robinson": "/players/usa_miles_robinson.jpg",
  "tim ream": "/players/usa_tim_ream.jpg",
  "alex freeman": "/players/usa_alex_freeman.jpg",
  "max arfsten": "/players/usa_max_arfsten.jpg",
  "mark mckenzie": "/players/usa_mark_mckenzie.jpg",
  "joe scally": "/players/usa_joe_scally.jpg",
  "tyler adams": "/players/usa_tyler_adams.jpg",
  "giovanni reyna": "/players/usa_giovanni_reyna.jpg",
  "weston mckennie": "/players/usa_weston_mckennie.jpg",
  "sebastian berhalter": "/players/usa_sebastian_berhalter.jpg",
  "cristian roldan": "/players/usa_cristian_roldan.jpg",
  "malik tillman": "/players/usa_malik_tillman.jpg",
  "ricardo pepi": "/players/usa_ricardo_pepi.jpg",
  "christian pulisic": "/players/usa_christian_pulisic.jpg",
  "brenden aaronson": "/players/usa_brenden_aaronson.jpg",
  "haji wright": "/players/usa_haji_wright.jpg",
  "folarin balogun": "/players/usa_folarin_balogun.jpg",
  "timothy weah": "/players/usa_timothy_weah.jpg",
  "alex zendejas": "/players/usa_alex_zendejas.jpg",
  "sergio rochet": "/players/uru_sergio_rochet.jpg",
  "santiago mele": "/players/uru_santiago_mele.jpg",
  "fernando muslera": "/players/uru_fernando_muslera.jpg",
  "jose maria gimenez": "/players/uru_jose_maria_gimenez.jpg",
  "sebastian caceres": "/players/uru_sebastian_caceres.jpg",
  "ronald araujo": "/players/uru_ronald_araujo.jpg",
  "guillermo varela": "/players/uru_guillermo_varela.jpg",
  "mathias olivera": "/players/uru_mathias_olivera.jpg",
  "matias vina": "/players/uru_matias_vina.jpg",
  "santiago bueno": "/players/uru_santiago_bueno.jpg",
  "manuel ugarte": "/players/uru_manuel_ugarte.jpg",
  "rodrigo bentancur": "/players/uru_rodrigo_bentancur.jpg",
  "nicolas de la cruz": "/players/uru_nicolas_de_la_cruz.jpg",
  "federico valverde": "/players/uru_federico_valverde.jpg",
  "giorgian de arrascaeta": "/players/uru_giorgian_de_arrascaeta.jpg",
  "agustin canobbio": "/players/uru_agustin_canobbio.jpg",
  "maxi araujo": "/players/uru_maxi_araujo.jpg",
  "joaquin piquerez": "/players/uru_joaquin_piquerez.jpg",
  "juan manuel sanabria": "/players/uru_juan_manuel_sanabria.jpg",
  "rodrigo zalazar": "/players/uru_rodrigo_zalazar.jpg",
  "darwin nunez": "/players/uru_darwin_nunez.jpg",
  "facundo pellistri": "/players/uru_facundo_pellistri.jpg",
  "brian rodriguez": "/players/uru_brian_rodriguez.jpg",
  "rodrigo aguirre": "/players/uru_rodrigo_aguirre.jpg",
  "federico vinas": "/players/uru_federico_vinas.jpg",
  "utkir yusupov": "/players/uzb_utkir_yusupov.jpg",
  "abduvohid nematov": "/players/uzb_abduvohid_nematov.jpg",
  "botirali ergashev": "/players/uzb_botirali_ergashev.jpg",
  "khojiakbar alijonov": "/players/uzb_khojiakbar_alijonov.jpg",
  "farrukh sayfiev": "/players/uzb_farrukh_sayfiev.jpg",
  "rustam ashurmatov": "/players/uzb_rustam_ashurmatov.jpg",
  "sherzod nasrullaev": "/players/uzb_sherzod_nasrullaev.jpg",
  "umar eshmurodov": "/players/uzb_umar_eshmurodov.jpg",
  "abdulla abdullaev": "/players/uzb_abdulla_abdullaev.jpg",
  "behruzjon karimov": "/players/uzb_behruzjon_karimov.jpg",
  "avazbek ulmasaliyev": "/players/uzb_avazbek_ulmasaliyev.jpg",
  "jakhongir urozov": "/players/uzb_jakhongir_urozov.jpg",
  "akmal mozgovoy": "/players/uzb_akmal_mozgovoy.jpg",
  "otabek shukurov": "/players/uzb_otabek_shukurov.jpg",
  "jamshid iskanderov": "/players/uzb_jamshid_iskanderov.jpg",
  "odiljon xamrobekov": "/players/uzb_odiljon_xamrobekov.jpg",
  "ruslanbek jiyanov": "/players/uzb_ruslanbek_jiyanov.jpg",
  "oston urunov": "/players/uzb_oston_urunov.jpg",
  "dostonbek khamdamov": "/players/uzb_dostonbek_khamdamov.jpg",
  "azizjon ganiev": "/players/uzb_azizjon_ganiev.jpg",
  "abbosbek fayzullaev": "/players/uzb_abbosbek_fayzullaev.jpg",
  "sherzod esanov": "/players/uzb_sherzod_esanov.jpg",
  "eldor shomurodov": "/players/uzb_eldor_shomurodov.jpg",
  "azizbek amonov": "/players/uzb_azizbek_amonov.jpg",
  "igor sergeev": "/players/uzb_igor_sergeev.jpg",
};

/**
 * Returns a real, downloaded player face image URL or imported asset.
 * 
 * @param {string} playerName - The name of the player.
 * @param {string} [countryName] - The player's country.
 * @returns {string} The image URL or asset.
 */
export function getPlayerImageUrl(playerName, countryName = '') {
  if (!playerName) return null;

  const name = playerName.trim();
  const lowerName = name.toLowerCase();

  // Return direct mapping if exists
  if (localPlayerFiles[lowerName]) {
    return localPlayerFiles[lowerName];
  }

  // Accent-insensitive and character normalization
  const normalized = name.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  const team = (countryName || '').toLowerCase().trim();

  // Direct matches after normalization
  if (normalized === 'lionel messi' || normalized === 'messi') return '/players/messi.png';
  if (normalized === 'kylian mbappe') return '/players/mbappe.png';
  if (normalized === 'cristiano ronaldo') return '/players/ronaldo.png';

  // Ronaldo override: Brazil legend vs Portugal superstar
  if (normalized === 'ronaldo') {
    const isBrazil = team.includes('brazil') || team.includes('bra') || name.toLowerCase().includes('nazario');
    return isBrazil ? '/players/ronaldo_nazario.png' : '/players/ronaldo.png';
  }

  // Legend Player mappings
  if (normalized === 'pele') return '/players/pele.png';
  if (normalized === 'diego maradona' || normalized === 'maradona') return '/players/maradona.png';
  if (normalized === 'zinedine zidane' || normalized === 'zidane') return '/players/zidane.png';
  if (normalized === 'franz beckenbauer' || normalized === 'beckenbauer') return '/players/beckenbauer.png';
  if (normalized === 'johan cruyff' || normalized === 'cruyff') return '/players/cruyff.png';
  if (normalized === 'michel platini' || normalized === 'platini') return '/players/platini.png';
  if (normalized === 'lothar matthaus' || normalized === 'matthaus') return '/players/matthaus.png';
  if (normalized === 'garrincha') return '/players/garrincha.png';
  if (normalized === 'miroslav klose' || normalized === 'klose') return '/players/klose.png';
  if (normalized === 'gerd muller' || normalized === 'gerd mueller') return '/players/mueller.png';
  if (normalized === 'roberto carlos') return '/players/roberto_carlos.png';
  if (normalized === 'cafu') return '/players/cafu.png';
  if (normalized === 'rivaldo') return '/players/rivaldo.png';
  if (normalized === 'ronaldinho') return '/players/ronaldinho.png';
  if (normalized === 'andres iniesta' || normalized === 'iniesta') return '/players/iniesta.png';
  if (normalized === 'neymar' || normalized === 'neymar jr') return '/players/neymar.png';
  if (normalized === 'luka modric' || normalized === 'modric') return '/players/modric.png';
  if (normalized === 'davor suker' || normalized === 'suker') return '/players/suker.png';

  // Strip spaces to match key legends
  const normalizedKey = normalized.replace(/\s+/g, '');
  const specialLegends = {
    'davidvilla': '/players/villa.png',
    'thierryhenry': '/players/henry.png',
    'waynerooney': '/players/rooney.png',
    'manuelneuer': '/players/neuer.png',
    'gianluigibuffon': '/players/buffon.png',
    'tonikroos': '/players/toni_kroos.png',
    'didierdeschamps': '/players/deschamps.png',
    'paulpogba': '/players/pogba.png',
    'antoinegriezmann': '/players/griezmann.png',
    'robertobaggio': '/players/baggio.png',
    'francobaresi': '/players/baresi.png',
    'hristostoichkov': '/players/stoichkov.png',
    'karlheinzrummenigge': '/players/rummenigge.png',
    'paolorossi': '/players/rossi.png',
    'mariokempes': '/players/kempes.png',
    'bobbymoore': '/players/bobby_moore.png',
    'geoffhurst': '/players/geoff_hurst.png',
    'bobbycharlton': '/players/bobby_charlton.png',
    'justfontaine': '/players/fontaine.png',
    'josefmasopust': '/players/masopust.png',
    'uweseeler': '/players/seeler.png',
    'jairzinho': '/players/jairzinho.png',
    'rivellino': '/players/rivelino.png',
    'robrensenbrink': '/players/rensenbink.png',
    'osvaldoardiles': '/players/ardiles.png',
    'danielpassarella': '/players/passarella.png',
    'haraldschumacher': '/players/schumacher.png',
    'garylineker': '/players/lineker.png',
    'salvatoreschillaci': '/players/schillaci.png',
    'dennisbergkamp': '/players/bergkamp.png',
    'gabrielbatistuta': '/players/batistuta.png',
    'michaelowen': '/players/owen.png',
    'philipplahm': '/players/lahm.png',
    'bastianschweinsteiger': '/players/schweinsteiger.png',
    'hugolloris': '/players/lloris.png',
    'oliviergiroud': '/players/giroud.png',
    'xavi': '/players/xavi.png',
    'xavihernandez': '/players/xavi.png'
  };

  if (specialLegends[normalizedKey]) {
    return specialLegends[normalizedKey];
  }

  // Local assets fallback
  if (normalized.includes("jimenez")) {
    return '/players/gimenez.png';
  }
  if (normalized.includes("jonathan david") || (normalized === "david" && team === "canada")) {
    return '/players/david.png';
  }
  if (normalized.includes("eustaquio")) {
    return '/players/eustaquio.png';
  }
  if (normalized.includes("johnston")) {
    return '/players/johnston.png';
  }
  if (normalized.includes("shaffelburg")) {
    return '/players/shaffelburg.png';
  }

  // Fallback: No external/unverified image upload, return null so local UI renders name & badge initials
  return null;
}

export function getPlayerInitials(name) {
  if (!name) return '?';
  const parts = name.trim().split(/\s+/);
  if (parts.length === 1) return parts[0].substring(0, 2).toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}

export function PlayerAvatar({ name, country = '', size = 40, style = {}, className = '' }) {
  const [hasError, setHasError] = useState(false);
  const src = getPlayerImageUrl(name, country);

  if (!src || hasError) {
    const initials = getPlayerInitials(name);
    return React.createElement('div', {
      className: `player-avatar-fallback ${className}`,
      style: {
        width: size,
        height: size,
        borderRadius: '50%',
        background: 'linear-gradient(135deg, var(--neon-cyan, #00f3ff), var(--neon-purple, #8b5cf6))',
        color: '#fff',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '700',
        fontSize: Math.max(10, Math.floor(size * 0.38)),
        boxShadow: '0 2px 8px rgba(0,0,0,0.25)',
        border: '1px solid rgba(255,255,255,0.2)',
        textTransform: 'uppercase',
        flexShrink: 0,
        userSelect: 'none',
        ...style
      },
      title: name
    }, initials);
  }

  return React.createElement('img', {
    src: src,
    alt: name,
    className: className,
    onError: () => setHasError(true),
    style: {
      width: size,
      height: size,
      borderRadius: '50%',
      objectFit: 'cover',
      flexShrink: 0,
      ...style
    }
  });
}



